# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/prueba04',
                'doc_host': 'https://Itzelep.github.io',
                'git_url': 'https://github.com/Itzelep/prueba04',
                'lib_path': 'prueba04'},
  'syms': {'prueba04.core': {'prueba04.core.foo': ('core.html#foo', 'prueba04/core.py')}}}
