# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['saludo', 'saludo_a']

# %% ../nbs/00_core.ipynb 3
def saludo ():
    """Imprime Hola"""
    print("Hola")
    return

saludo()

#| export
def saludo_a(to):
    """Imprime Hola a un nombre"""
    print("Hola",to)
    print("Espero te encuentres bien")
    return

saludo_a("Raul")
show_doc(saludo_a)
